version: "3.8"

services:
  app:
    build:
      context: ./docker/app
    container_name: itech_warranty_dashboard
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=production
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: itech_warranty_dashboard_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app

  db:
    image: mariadb:10.6
    container_name: itech_warranty_dashboard_db
    environment:
      - MARIADB_DATABASE=itech_warranty_dashboard
      - MARIADB_USER=root
      - MARIADB_PASSWORD=Indoteknik898@
      - MARIADB_ROOT_PASSWORD=Indoteknik898@
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"

networks:
  default:
    name: laravel_net